171 bitmap from ink
DrawYourPath/DrawYourPath pull request #182
Opened 2023-05-09 17:20 UTC by clementcharmillot

closes #171

2023-05-15 12:34 UTC, HoLuDyEr requested changes
Overall it is a good PR. The code is clean, easy to understand and well documented.
I only have a small remark for some code duplication.

2023-05-15 12:34 UTC, HoLuDyEr commented on app/src/main/java/com/epfl/drawyourpath/utils/Utils.kt
> +        }.let { Point.create(it.first, it.second) }
These two functions are quite similar even if one uses the other. One alternative I can think of is : 
```kotlin
fun getSmallestPoint(strokes: List<Stroke>): Point =
        strokes.map { it.points }.flatten().fold(Pair(Float.MAX_VALUE, Float.MAX_VALUE)) { acc, point ->
            Pair(min(acc.first, point.x), min(acc.second, point.y))
        }.let { Point.create(it.first, it.second) }
```
and the other
```kotlin
fun getSmallestPoint(stroke: Stroke): Point = getSmallestPoint(listOf(stroke))
```

2023-05-16 12:10 UTC, clementcharmillot commented
Thanks for the review, I've addressed both remarks. Let me know if there's anything more.

2023-05-16 12:50 UTC, HoLuDyEr approved these changes
Thank you for the changes.
You can merge now.

2023-05-16 13:05 UTC, merged