164 reformat trophies
DrawYourPath/DrawYourPath pull request #189
Opened 2023-05-15 20:15 UTC by HoLuDyEr

This PR reformats the trophies and milestones.

![image](https://github.com/DrawYourPath/DrawYourPath/assets/61149724/57f1e9fc-ea65-4f86-b3f2-4f272e8f4091)

![image](https://github.com/DrawYourPath/DrawYourPath/assets/61149724/24595d38-7618-4f46-936d-1dcbf17a0cee)

closes #164 #162

2023-05-16 20:52 UTC, HugoHof requested changes
Thank you for your excellent work. The code is clean and well structured. The code is entirely tested (you got 100%of coverage, well done). There is few remarks and we are good. 
Don't hesitate if you have any question .

2023-05-16 20:52 UTC, HugoHof commented on app/src/androidTest/java/com/epfl/drawyourpath/mainpage/fragments/ChallengeFragmentTest.kt
> +    fun modifyDistanceGoalDisplayNewDistanceGoal() {
This test is commented. Maybe add a TODO to explain the reason or delete it.

2023-05-16 20:52 UTC, HugoHof commented on app/src/androidTest/java/com/epfl/drawyourpath/mainpage/fragments/ChallengeFragmentTest.kt
> +    fun modifyTimeGoalDisplayNewTimeGoal() {
Same here : This test is commented. Maybe add a TODO to explain the reason or delete it.

2023-05-16 20:52 UTC, HugoHof commented on app/src/androidTest/java/com/epfl/drawyourpath/mainpage/fragments/ChallengeFragmentTest.kt
> +            ChallengeFragment::class.java,
Same here : This test is commented. Maybe add a TODO to explain the reason or delete it.

2023-05-16 20:52 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/challenge/milestone/Milestone.kt
> +    val dateAsString: String = Utils.getDateAsString(date),
Maybe you can add a default value for the drawable, like you have done for the trophy.

2023-05-16 20:52 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/challenge/milestone/Milestone.kt
> +    val dateAsString: String = Utils.getDateAsString(date),
Why the date is of type string here ? Maybe it can be better if it is in LocalDate type.

2023-05-16 20:52 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/challenge/milestone/Milestone.kt
I don't really understand why there is MilestoneEnum and a Milestone object. Since the milestone are predefined in the enum, the Milestone object is useful in which situation ?

2023-05-16 20:52 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/challenge/milestone/Milestone.kt
Or maybe the Milestone object can only be composed of a MilestoneEnum value and a date value.

2023-05-16 20:52 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/challenge/trophy/Trophy.kt
> +    companion object {
Maybe add a comment to explain in which situation the sample of trophy will be used (in test scenarios for example...)

2023-05-16 20:52 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/challenge/trophy/TrophyViewAdapter.kt
> + */
Maybe edit the comment to : to display the list of Trophy

2023-05-17 08:21 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/challenge/milestone/Milestone.kt
> +    companion object {
Maybe. add a comment to explain why this companion object is useful for.

2023-05-17 12:52 UTC, HoLuDyEr commented on app/src/main/java/com/epfl/drawyourpath/challenge/milestone/Milestone.kt
I created this class so that it is easier to use and display the milestone on the UI, also it changes the name of the MilestoneEnum or else it would be in ALL_CAPS. There is also a constructor from MilstoneEnum to Milestone.

2023-05-17 15:30 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/challenge/milestone/Milestone.kt
Ok, thank you for the clarification.

2023-05-17 15:38 UTC, merged