54 user profile UI
DrawYourPath/DrawYourPath pull request #64
Opened 2023-03-21 19:09 UTC by clementcharmillot

2023-03-22 19:59 UTC, clementcharmillot commented
@HugoHof I ping you as you are in charge of the database and the data we store for an user. Do you have an idea of stored data that I could add to this profile view that I could have missed?

2023-03-22 20:15 UTC, HugoHof commented
> @HugoHof I ping you as you are in charge of the database and the data we store for an user. Do you have an idea of stored data that I could add to this profile view that I could have missed?

Maybe you can add the age of the user, the friendlist(with the friend's username). The current distance, activity time and nb Of path goals.

You can also add the average time the runner made to run one kilometer(for ex 5,00min/km). And the number of times the user has accomplish his goals.

2023-03-23 19:51 UTC, clementcharmillot commented
@HugoHof Thanks for the info. Added the friend list and the goals reached. I didn't add the age as it doesn't look really relevant with other statistics.

2023-03-24 12:24 UTC, HugoHof requested changes
This is a good UI to show the user profile. The code is very clean and there is useful helpers function in the fragments to facilitate the link between the diffrentsm data in the xml elements ids. I have just make some small comments with some suggestion. Maybe in the future you can add a method in the ProfileFragment to directly link all in the element of UserModel to the corresponding xml ids.

2023-03-27 09:26 UTC, clementcharmillot commented on app/src/main/java/com/epfl/drawyourpath/mainpage/fragments/ProfileFragment.kt
> +
I've added an action when we click on the trophy count. The idea is to redirect to the trophy fragment. We might also show the trophies in a modal. What do you think?

2023-03-27 12:00 UTC, HugoHof commented on app/src/main/java/com/epfl/drawyourpath/mainpage/fragments/ProfileFragment.kt
> +
It's a goof idea.

2023-03-27 18:23 UTC, merged